### ISSUE TITLE
The website isn’t mobile friendly 

### ISSUE THREAD

**Issue by rodneyosodo** [4adhis/LINUS_Personal_Website#3]
![847A61E9-DD5D-4FCF-BC79-CFC09F3839CB](https://user-images.githubusercontent.com/28790446/76895493-2c458b80-68a1-11ea-8113-09bc91a2326c.png)
The site isn’t the same as the desk
![715D2034-7524-4415-9F80-14F905DC2A3B](https://user-images.githubusercontent.com/28790446/76895507-32d40300-68a1-11ea-9d0b-bd1c8a9ca750.png) version

**Comment by Adhiambo-Cynthia** [comment]
That's what I'm working on. .I'm sorry who is this

**Comment by rodneyosodo** [comment]
Rodney

**Comment by Adhiambo-Cynthia** [comment]
ooww.....commented on what
